### ISSUE TITLE
RegisterActivityAsync(ActivityDescription activityDescription)

### ISSUE THREAD

**Issue by mirel-maestral** [gurmitteotia/guflow#18]
Could it be decorated with public modifier?

Is there a way to register activity/workflow by specifying description dynamically - not by using class attributes? 

All above applies to the Activity/Workflow.

**Comment by gurmitteotia** [comment]
Guflow allows you to dynamically provide Workflow/Activity description. This is already implemented in released version but not documented. I will update the documents.

You can provide ActivityDescription (and similarly WorkflowDescription) dynamically as below:
```cs
public class DownloadActivity : Activity
{
   private static ActivityDescription ActivityDescription()
    {
       return new ActivityDescription("1.0")
       {
           Name = "some name",
           DefaultTaskListName = "tasklist",
           Description = "desc",
           DefaultTaskPriority = 10,
           DefaultHeartbeatTimeout = TimeSpan.FromSeconds(2),
           DefaultScheduleToCloseTimeout = TimeSpan.FromSeconds(3),
           DefaultScheduleToStartTimeout = TimeSpan.FromSeconds(4),
           DefaultStartToCloseTimeout = TimeSpan.FromSeconds(5)
       };
    }
}
```
It will look for any static method (without any arguments)/property with ActivityDescription as return type and returned ActivityDescription will take priority over ActivityDescriptionAttribute.
Please look at the[ test cases](https://github.com/gurmitteotia/guflow/blob/master/Guflow.Tests/Worker/ActivityDescriptionTests.cs) for examples.


These methods were originally public but I made them private because they could have allowed developers to introduce bug. Consider following Activity:
```cs
[ActivityDescription("1.0")]
public class MyActivity :Activity{
	
}
```
Developer register the activity using following approach and assume she changes version of it..
```cs
var desc = ActivityDescription.FindOn<MyActivity>();
desc.Version = "2.0";
await domain.RegisteryActivityAsync(desc);
```

Now she try to schedule this activity in workflow:

```cs
public class MyWorkflow :Workflow
{
	public MyWorkflow()
	{
		ScheduleActivity<MyActivity>();
	}
} 
```

Now workflow read the version of MyActivity as "1.0" and it does not have any idea that this activity has been registered with version "2.0". Workflow will try to schedule the MyActivity with version "1.0" but that is not registered with AWS.

Hope it makes things clear?

**Comment by gurmitteotia** [comment]
I have updated the [activity registration](https://github.com/gurmitteotia/guflow/wiki/Activity-registration) and [workflow registration](https://github.com/gurmitteotia/guflow/wiki/Workflow-registration) documents.
