### ISSUE TITLE
Unit Tests Support for Activities and Workflows

### ISSUE THREAD

**Issue by alexzm1** [gurmitteotia/guflow#20]
I was wondering if there is a way to create unit tests of custom activities and workflows, saw in the project a project with Unit Tests but most of those methods used to create unit tests are Internal methods in the Guflow library project, also project's wiki doesn't seems to contain any section to create Unit Tests, is there any way we can create unit tests for our custom Activities and Workflows?

**Comment by gurmitteotia** [comment]
Yes you can. I will update the document.
**For workflow** you will write the automated tests using test double/fake activities as shown in [integration project](https://github.com/gurmitteotia/guflow/tree/master/Guflow.IntegrationTests).  I have intentionally not made unit testing of workflow public because as a library user you will not get needed reliability and value from them. e.g. for the following workflow, which we have discussed in other threads:
```cs
[WorkflowDescription("1.0")]
public class OrderWorkflow : Workflow
{
     public OrderWorkflow(TimeSpan gracePeriod)
     {
          ScheduleTimer("GracePeriod").FireAfter(gracePeriod)
                                                          .OnCancel(_=>Jump.ToActivity<CancelOrder>())
                                                          .OnFired(_=>Jump.toActivity<ShipOrder>());

         ScheduleActivity<CancelOrder>().AfterTimer("GracePeriod");
         ScheduleActivity<ShipOrder>().AfterTimer("GracePeriod");
     }

    [WorkflowEvent(EventName.CancelRequest)]
    public WorkflowAction Cancel()
    {
         if(Timer("GracePeriod").IsActive)
                return CancelRequest.ForTimer("GracePeriod");
        return Ignore;
    }
}
```
You will get huge benefits if you will write following behavioural tests using fake/test double activities. I can describe some these tests as:
```
  Workflow_is_cancelled_when_cancellation_is_requested_within_grace_period
  Cancel_request_is_ignored_when_made_after_grace_period.
  //...
```

However if you write the unit tests for workflow as I have written [here](https://github.com/gurmitteotia/guflow/blob/master/Guflow.Tests/Decider/DeflowAlgorithmTests.cs) then I can see following problem:
* You will be coupled with internals of library
* You are more likely to test Guflow library than your business logic
* You are likely to find bugs in production than in tests. Remember you can return any combination of decisions to SWF but not all of them are valid. e.g. CancelRequest.ForTimer("GracePeriod") is not valid of non active timers. You're unlikely to catch such restrictions in unit tests.

**For activities** you write public methods in [different style](https://github.com/gurmitteotia/guflow/wiki/Activity-method) just like any other classes and are pretty much unit testable. If you pass any dependency to your activity then Guflow can not create the instance of it and you need to supply it with activity creator as show in below example:

```cs
 //Suppose you have a service locator or IoC container which can create the instances of activity

ServiceLocator.Configure();
var host = _domain.Host(activites, t=>ServiceLocator.Create(t));
...
```
However prior to version [1.1.16](https://www.nuget.org/packages/Guflow/1.1.16) you could not have written the unit tests for activity for every situation but it is now fixed.

**Comment by alexzm1** [comment]
Thank! just tested it with Activities and it seems to be working now! I really appreciate it

**Comment by gurmitteotia** [comment]
That is good. Glad that it is working for you.
